/**
 * Reconstructed from the client's live Tally export for "TAH GLOBAL HEALTHCARE
 * PVT LTD" (the legal entity behind the "Axten Hospitals" org, org-avani-default):
 *   - Groups- Tally.xls  (37 groups)
 *   - Ledgers - Tally (1).xls (346 ledgers)
 *
 * The source .xls files list groups/ledgers as a flat, pre-order depth-first
 * walk with NO indentation preserved in the export (confirmed by inspecting
 * the raw xlsx cell XML — no indent style, no column-offset encoding). Parent
 * relationships below were reconstructed from (a) Tally's fixed, well-known
 * standard primary-group taxonomy for the 18 root groups, and (b) positional
 * nesting for the 19 custom sub-groups. The reconstruction is internally
 * consistent: exactly 37 groups and exactly 346 ledgers, matching the source
 * files' own footer counts ("37 Group(s)", "346 Ledger(s)").
 *
 * Two items have genuine residual ambiguity worth a finance-team sanity check
 * before relying on them for reporting (flagged inline below):
 *   1. The "PRISTYNCARE" sub-group under Sundry Debtors contains a mix of
 *      named corporate debtors (GHV, AVISE HOSPITAL, EDEN HOSPITAL, etc.) and
 *      payment-channel-looking names (CARD, Cheque, PAYING, RTGS_NEFT, UPI) —
 *      this reads like a TPA settlement-channel breakdown, but that's an
 *      inference, not a certainty.
 *   2. "Employee Benefit" appears twice: once as a sub-group of Indirect
 *      Expenses (containing ledger "Staff Welfare"), and once again as a
 *      same-named ledger directly under Indirect Expenses. Tally allows a
 *      ledger and a group to share a name; both are preserved as distinct
 *      entities below.
 */

export type TallyAccountType = 'Asset' | 'Liability' | 'Equity' | 'Revenue' | 'Expense';

export interface TallyGroupDef {
  code: string;
  name: string;
  parent_code: string | null;
  account_type: TallyAccountType;
}

export interface TallyLedgerDef {
  name: string;
  group_code: string;
}

// ── 37 Groups (18 standard Tally primary groups + 19 custom sub-groups) ────
export const TALLY_GROUPS: TallyGroupDef[] = [
  // Standard Tally primary groups (root, parent_code: null)
  { code: 'TLY-BRANCH-DIVISIONS', name: 'Branch / Divisions', parent_code: null, account_type: 'Asset' },
  { code: 'TLY-CAPITAL-ACCOUNT', name: 'Capital Account', parent_code: null, account_type: 'Equity' },
  { code: 'TLY-RESERVES-SURPLUS', name: 'Reserves & Surplus', parent_code: null, account_type: 'Equity' },
  { code: 'TLY-CURRENT-ASSETS', name: 'Current Assets', parent_code: null, account_type: 'Asset' },
  { code: 'TLY-SUNDRY-DEBTORS', name: 'Sundry Debtors', parent_code: null, account_type: 'Asset' },
  { code: 'TLY-CURRENT-LIABILITIES', name: 'Current Liabilities', parent_code: null, account_type: 'Liability' },
  { code: 'TLY-SUNDRY-CREDITORS', name: 'Sundry Creditors', parent_code: null, account_type: 'Liability' },
  { code: 'TLY-DIRECT-EXPENSES', name: 'Direct Expenses', parent_code: null, account_type: 'Expense' },
  { code: 'TLY-DIRECT-INCOMES', name: 'Direct Incomes', parent_code: null, account_type: 'Revenue' },
  { code: 'TLY-FIXED-ASSETS', name: 'Fixed Assets', parent_code: null, account_type: 'Asset' },
  { code: 'TLY-INDIRECT-EXPENSES', name: 'Indirect Expenses', parent_code: null, account_type: 'Expense' },
  { code: 'TLY-INDIRECT-INCOMES', name: 'Indirect Incomes', parent_code: null, account_type: 'Revenue' },
  { code: 'TLY-INVESTMENTS', name: 'Investments', parent_code: null, account_type: 'Asset' },
  { code: 'TLY-LOANS-LIABILITY', name: 'Loans (Liability)', parent_code: null, account_type: 'Liability' },
  { code: 'TLY-MISC-EXPENSES-ASSET', name: 'Misc. Expenses (ASSET)', parent_code: null, account_type: 'Asset' },
  { code: 'TLY-PURCHASE-ACCOUNTS', name: 'Purchase Accounts', parent_code: null, account_type: 'Expense' },
  { code: 'TLY-SALES-ACCOUNTS', name: 'Sales Accounts', parent_code: null, account_type: 'Revenue' },
  { code: 'TLY-SUSPENSE-AC', name: 'Suspense A/c', parent_code: null, account_type: 'Asset' },

  // Custom sub-groups
  { code: 'TLY-BANK-ACCOUNTS', name: 'Bank Accounts', parent_code: 'TLY-CURRENT-ASSETS', account_type: 'Asset' },
  { code: 'TLY-CASH-IN-HAND', name: 'Cash-in-Hand', parent_code: 'TLY-CURRENT-ASSETS', account_type: 'Asset' },
  { code: 'TLY-DEPOSITS-ASSET', name: 'Deposits (Asset)', parent_code: 'TLY-CURRENT-ASSETS', account_type: 'Asset' },
  { code: 'TLY-FIXED-DEPOSITS', name: 'Fixed Deposits', parent_code: 'TLY-DEPOSITS-ASSET', account_type: 'Asset' },
  { code: 'TLY-LOANS-ADVANCES-ASSET', name: 'Loans & Advances (Asset)', parent_code: 'TLY-CURRENT-ASSETS', account_type: 'Asset' },
  { code: 'TLY-STOCK-IN-HAND', name: 'Stock-in-Hand', parent_code: 'TLY-CURRENT-ASSETS', account_type: 'Asset' },
  { code: 'TLY-PRISTYNCARE-GRP', name: 'PRISTYNCARE', parent_code: 'TLY-SUNDRY-DEBTORS', account_type: 'Asset' }, // see ambiguity note 1
  { code: 'TLY-DUTIES-TAXES', name: 'Duties & Taxes', parent_code: 'TLY-CURRENT-LIABILITIES', account_type: 'Liability' },
  { code: 'TLY-EMPLOYEE', name: 'EMPLOYEE', parent_code: 'TLY-CURRENT-LIABILITIES', account_type: 'Liability' },
  { code: 'TLY-AVISE-STAFF', name: 'AVISE STAFF', parent_code: 'TLY-EMPLOYEE', account_type: 'Liability' },
  { code: 'TLY-CORPORATE-OFFICE', name: 'Corporate Office', parent_code: 'TLY-EMPLOYEE', account_type: 'Liability' },
  { code: 'TLY-PROVISIONS', name: 'Provisions', parent_code: 'TLY-CURRENT-LIABILITIES', account_type: 'Liability' },
  { code: 'TLY-RENT-PAYABLE', name: 'RENT PAYABLE', parent_code: 'TLY-PROVISIONS', account_type: 'Liability' },
  { code: 'TLY-OUTSIDE-DOCTOR', name: 'OUTSIDE DOCTOR', parent_code: 'TLY-SUNDRY-CREDITORS', account_type: 'Liability' },
  { code: 'TLY-EMPLOYEE-BENEFIT', name: 'Employee Benefit', parent_code: 'TLY-INDIRECT-EXPENSES', account_type: 'Expense' }, // see ambiguity note 2
  { code: 'TLY-BANK-OD-AC', name: 'Bank OD A/c', parent_code: 'TLY-LOANS-LIABILITY', account_type: 'Liability' },
  { code: 'TLY-SECURED-LOANS', name: 'Secured Loans', parent_code: 'TLY-LOANS-LIABILITY', account_type: 'Liability' },
  { code: 'TLY-UNSECURED-LOANS', name: 'Unsecured Loans', parent_code: 'TLY-LOANS-LIABILITY', account_type: 'Liability' },
  { code: 'TLY-PEDAL-START', name: 'PEDAL START', parent_code: 'TLY-UNSECURED-LOANS', account_type: 'Liability' },
];

// ── 346 Ledgers ──────────────────────────────────────────────────────────
export const TALLY_LEDGERS: TallyLedgerDef[] = [
  // Bank Accounts (4)
  { name: 'DBS BANK INDIA LIMITED', group_code: 'TLY-BANK-ACCOUNTS' },
  { name: 'ICICI Bank -072005500811', group_code: 'TLY-BANK-ACCOUNTS' },
  { name: 'INDIAN BANK - 5245', group_code: 'TLY-BANK-ACCOUNTS' },
  { name: 'INDIAN BANK - 7199', group_code: 'TLY-BANK-ACCOUNTS' },
  // Cash-in-Hand (2)
  { name: 'Cash', group_code: 'TLY-CASH-IN-HAND' },
  { name: 'PETTY CASH', group_code: 'TLY-CASH-IN-HAND' },
  // Fixed Deposits (3)
  { name: 'FD 8290104677', group_code: 'TLY-FIXED-DEPOSITS' },
  { name: 'FD 8301032863', group_code: 'TLY-FIXED-DEPOSITS' },
  { name: 'FD 8311042928', group_code: 'TLY-FIXED-DEPOSITS' },
  // Loans & Advances (Asset) (5)
  { name: 'AJAY ENTERPRISES', group_code: 'TLY-LOANS-ADVANCES-ASSET' },
  { name: 'PATIALAHEALTHCARE-ADVANCE', group_code: 'TLY-LOANS-ADVANCES-ASSET' },
  { name: 'SHREY TEXTILES - ADVANCE', group_code: 'TLY-LOANS-ADVANCES-ASSET' },
  { name: 'STAFF ADVANCE', group_code: 'TLY-LOANS-ADVANCES-ASSET' },
  { name: 'ZAO CARE TECHNOLOGY', group_code: 'TLY-LOANS-ADVANCES-ASSET' },
  // PRISTYNCARE sub-group under Sundry Debtors (12) — see ambiguity note 1
  { name: 'GHV ADVANCED CARE PVT. LTD.', group_code: 'TLY-PRISTYNCARE-GRP' },
  { name: 'AVISE HOSPITAL', group_code: 'TLY-PRISTYNCARE-GRP' },
  { name: 'CARD', group_code: 'TLY-PRISTYNCARE-GRP' },
  { name: 'Cheque', group_code: 'TLY-PRISTYNCARE-GRP' },
  { name: 'EDEN HOSPITAL PVT LTD', group_code: 'TLY-PRISTYNCARE-GRP' },
  { name: 'ICI HOSPITAL', group_code: 'TLY-PRISTYNCARE-GRP' },
  { name: 'PAYING', group_code: 'TLY-PRISTYNCARE-GRP' },
  { name: 'PRISTYNCARE', group_code: 'TLY-PRISTYNCARE-GRP' },
  { name: 'RTGS_NEFT', group_code: 'TLY-PRISTYNCARE-GRP' },
  { name: 'SARITA ENTERPRISES', group_code: 'TLY-PRISTYNCARE-GRP' },
  { name: 'SSB HOSPITAL', group_code: 'TLY-PRISTYNCARE-GRP' },
  { name: 'UPI', group_code: 'TLY-PRISTYNCARE-GRP' },
  // Fixed Assets (4)
  { name: 'LAPTOP & COMPUTER', group_code: 'TLY-FIXED-ASSETS' },
  { name: 'MEDICAL EQUIPMENTS', group_code: 'TLY-FIXED-ASSETS' },
  { name: 'Phone', group_code: 'TLY-FIXED-ASSETS' },
  { name: 'WEBSITE', group_code: 'TLY-FIXED-ASSETS' },
  // Duties & Taxes (10)
  { name: '192-TDS ON SALARY', group_code: 'TLY-DUTIES-TAXES' },
  { name: '194A-TDS ON INTEREST', group_code: 'TLY-DUTIES-TAXES' },
  { name: 'EPFO PAYABLE', group_code: 'TLY-DUTIES-TAXES' },
  { name: 'ESIC PAYABLE', group_code: 'TLY-DUTIES-TAXES' },
  { name: 'GST PAYABLE', group_code: 'TLY-DUTIES-TAXES' },
  { name: 'TDS-94C CO.-2%', group_code: 'TLY-DUTIES-TAXES' },
  { name: 'TDS 94C NON CO.-1%', group_code: 'TLY-DUTIES-TAXES' },
  { name: 'TDS 94I-0.50%', group_code: 'TLY-DUTIES-TAXES' },
  { name: 'TDS 94I-NONCO', group_code: 'TLY-DUTIES-TAXES' },
  { name: 'TDS 94J-10%', group_code: 'TLY-DUTIES-TAXES' },
  // AVISE STAFF payroll (25)
  { name: 'ABHISHEK - PAYROLL', group_code: 'TLY-AVISE-STAFF' },
  { name: 'ANAM - PAROLL', group_code: 'TLY-AVISE-STAFF' },
  { name: 'DEEPAK ARYA - PAYROLL', group_code: 'TLY-AVISE-STAFF' },
  { name: 'DIVYA - PAROLL', group_code: 'TLY-AVISE-STAFF' },
  { name: 'HEMA RAWAT - PAYROLL', group_code: 'TLY-AVISE-STAFF' },
  { name: 'ISHA', group_code: 'TLY-AVISE-STAFF' },
  { name: 'JAY PRAKASH SINGH - PAYROLL', group_code: 'TLY-AVISE-STAFF' },
  { name: 'KAJAL PATI - PAYROLL', group_code: 'TLY-AVISE-STAFF' },
  { name: 'KAPIL - PAYROLL', group_code: 'TLY-AVISE-STAFF' },
  { name: 'MANJEET - PAYROLL', group_code: 'TLY-AVISE-STAFF' },
  { name: 'MANJU - PAYROLL', group_code: 'TLY-AVISE-STAFF' },
  { name: 'MEHAR - PAYROLL', group_code: 'TLY-AVISE-STAFF' },
  { name: 'NAHAR SINGH - PAYROLL', group_code: 'TLY-AVISE-STAFF' },
  { name: 'NANISI YADAV - PAYROLL', group_code: 'TLY-AVISE-STAFF' },
  { name: 'PARVEEN SINGH - PAYROLL', group_code: 'TLY-AVISE-STAFF' },
  { name: 'PAWAN KUMAR - PAYROLL', group_code: 'TLY-AVISE-STAFF' },
  { name: 'RAUSHAN KUMAR - PAYROLL', group_code: 'TLY-AVISE-STAFF' },
  { name: 'REENA - PAYROLL', group_code: 'TLY-AVISE-STAFF' },
  { name: 'SACHIN - PAYROLL', group_code: 'TLY-AVISE-STAFF' },
  { name: 'SACHIN SAXSENA - PAYROLL', group_code: 'TLY-AVISE-STAFF' },
  { name: 'SANJAY - PAYROLL', group_code: 'TLY-AVISE-STAFF' },
  { name: 'SARA - PAYROLL', group_code: 'TLY-AVISE-STAFF' },
  { name: 'SHEELU - PAYROLL', group_code: 'TLY-AVISE-STAFF' },
  { name: 'SHIVANI - PAYROLL', group_code: 'TLY-AVISE-STAFF' },
  { name: 'SUKANT - PAYROLL', group_code: 'TLY-AVISE-STAFF' },
  // Corporate Office payroll (64)
  { name: 'ABHISHEK - PAYROLL GURUGRAM', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'DEEPIKA SINGH - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'DHARMENDRA KUMAR YADAV - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'GAUTAM CHHABRA -PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'ISHIKA GUPTA - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'JAY KUMAR - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'MEENU - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'MOHIT KHETARPAL - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'NARESH PACHORI - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'RENU - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'RISHU KUMAR - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'ROHAN - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'SATISH KUMAR PANDEY - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'SURAJ - PAYROLL GURGRAM', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'SURBHI SRIVASTAVA - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'TANU SHARMA - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'UMESH KUMAR GAUTAM - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'VIRENDRA KUMAR - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'VISHAL SHUKLA - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'AJAY BAISOYA - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'AKANSHA SHARMA - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'AKASH - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'AMBHIKESH KUMAR JHA - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'AMIT - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'ANGRAJ - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'ANJALI - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'ANJU - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'ARMAN - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'BABITA - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'BITTOO RAI - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'CHARU SINHA - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'DEBNARAYAN BISWAS - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'DIVYA KUMARI - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'GEETA - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'HAIDER ALI - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'JYOTI KUMARI - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'KAVYA MEHRA - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'KHUSHBOO - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'MUKESH BEDWAL - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'NEETU - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'NISHU - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'NITIN RAUTHAN - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'NITISH KUMAR - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'PARAMJEET SINGH - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'POOJA NURSING - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'POOJA - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'PRACHI - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'PRIYANKA KUMARI - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'PUNEET KUMAR - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'RISHAB KHATRI - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'ROHIT NIGAM - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'SAGAR DAS - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'SAGAR - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'SANA ANSARI', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'SHAURYA - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'SHYAMA VATI - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'SONAM VERMA - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'SUMIT KUMAR - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'SUNITA KUMARI - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'SURAJ - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'TUSHAR - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'VISHWANATH YADAV - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'YASHIKA - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  { name: 'YATIN KHETARPAL - PAYROLL', group_code: 'TLY-CORPORATE-OFFICE' },
  // RENT PAYABLE (2)
  { name: 'HARGYAN SINGH', group_code: 'TLY-RENT-PAYABLE' },
  { name: 'MRINAL SINGH', group_code: 'TLY-RENT-PAYABLE' },
  // OUTSIDE DOCTOR (56)
  { name: 'AASHIMA CHOPRA', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'ABHAY SINGHAL', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'AKASH SHARMA IT', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'AKHILESH KUMAR', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'AMARNATH SAINI', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'ANIL KUMAR KALER', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'ANJALI PATWAL', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'ANUBHAV SANGWAN', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'ASHA MALHOTRA', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'AVYJNR HEALTH TEHNOLOGIES INDIA PVT LTD', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'BHAVYA', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'BIRJESH KUMAR THAKAN', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'BOBIN KUMAR', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'CHAND', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'COSMO CURE HEALTH', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'DEEPAK', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'DEVESH KUMAR', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'DHEERAJ', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'FLIPLIFE 180 PVT LTD', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'HARINDER SINGH TOMAR', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'HEALTHENSURE CARE SOLUTIONS PVT LTD', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'HIMANSHU MATHUR', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'LOKESH HANDA', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'MANSI DEWAN', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'MOHAMMAD SABIR', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'MOHAMMED TABISH RAYEE', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'MOHD ASJAD', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'MOHIT KUMAR', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'MOLECULE PHARMA CARE OF NAVEEN', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'MUKESH CARPENTER', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'NAJEEB AKHTAR', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'NAVDEEP CHHABRA', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'NAVEEN  KUMAR VERMA', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'NIRAJ KUMAR NIKUNJ', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'OPTIHEALTH SERVICES PVT LTD', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'PRAMOD KUMAR GULATI', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'PRATIKSHA SINGH', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'PRAVIN TIWARI', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'PULKIT ARORA', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'PURODHA', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'RAKESH LIONEL', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'RAVI KANT SHUKLA', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'RICHA KUMAR', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'SANJAY BANSAL', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'SAURABH KUMAR SINHA', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'SAURABH MOHAN', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'SHALINI PAL', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'SHIV CHOPRA', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'SUBHASHISH DAS', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'SUNNY BALIYAN', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'SURESH KUMAR KASANA', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'SUSHIL KUMAR', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'SWASTHY WELLCARE PVT LTD', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'TULEEKA SETHI', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'VANYA CLINIC-ANIL KALER', group_code: 'TLY-OUTSIDE-DOCTOR' },
  { name: 'VINEETA KAPOOR', group_code: 'TLY-OUTSIDE-DOCTOR' },
  // Sundry Creditors, direct (86) — general vendors, not under OUTSIDE DOCTOR
  { name: 'ACT FIBER NET', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'ADRECIPES DIGITAL PVT LTD', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'AJAY ENTERPRISES-CREDITORS', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'AJAY - SAMSUNG', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'AKASA COWORKING PVT LTD', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'ALPHA MRI & DIAGNOSTICS', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'AMAZON', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'A N AIR CONDITIONING', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'ANKIT STATIONERS', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'ANSH HOME DRESSING CARE', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'Apex Insurance Consultant Ltd', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'APOORVA PANDEY', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'ASHVEN HEALTH OPC PVT LTD', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'Bharti Airtel Limited', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'BIOTIC WASTE SOLUTIONS PVT.LTD.', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'BLOOD CENTRE OF TRITON HOSPITAL', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'BSES-100091608', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'BSES-100105622', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'BSES-150464047', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'CHAMAN SINGH', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'CUBE SOFTWARE PVT LTD', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'DIAMOND PEST CONTROL SERVICES', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'E2E Networks Limited', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'EDEN HOSPITAL A UNIT OF TAH GLOBAL HEALTHCARE PVT', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'EMAZE TECHNOLOGY', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'EROUTE TECHNOLOGIES PVT LTD', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'FACEBOOK', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'FIRE FLY PLACEMENT SERVICES', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'FORTIS FILT LTD.RAJQN DHALL HOSPITAL', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'GANGA DHAR DRYCLEANERS', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'GARNET PHARMACEUTICALS', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'Google', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'GRD ENTERPRISES', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'GUT CLINIC', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'HABIN DIETARY SRVICES', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'HAMII LAB INSTRUMENT', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'HEALTHOPIA DIAGNOSTICS', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'HRACCELERATE PARTNERS LLP', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'IMMUNITYASSURANCE PVT LTD', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'INDUSTRIAL SOLUTIONS', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'J.K. GENERATOR SERVICE CENTRE', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'K T Medical Instrument Services', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'KUSHWAHA AND COMPANY', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'LEDSAK TECHNOLOGIES PVT LTD', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'LOGIMINDS TECHNOLAB LLP', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'Manoj Kumar', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'M K CABLETRONIX', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'Naagar Electrical', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'NIDHI HEALTHCARE SERVICES', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'NOBLE DIAGNOSTICS', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'NPG INFOTECH SYSTEM', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'OAKLAND SYSTEM  PVT. LTD.', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'OUT OF HOME MEDIA GROUP', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'PATHCORE DIAGNOSTICS', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'PATIALAHEAL HEALTHCARE', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'P D PHARMAA', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'PRECISION INSTRUMENT INC.', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'PREM VATI-HOSTLE RENT', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'RAM SEWAK AND COM', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'RAY NURSING HOME', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'Refund Payable', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'ROCKMAN SECURITY PVT LTD', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'Saraswati Accountants Software Pvt Ltd', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'SATISH', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'SETH AIR PRODUCTS', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'SHAHBAZ TOMAR KHAN', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'SHAHJAHAN', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'SHIVI ENTERPRISES', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'SHREY TEXTILES - Creditors', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'SIGNAGE WPRLD', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'SIRBAS FLOWERS', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'SONY AIR COLL', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'SPD INDIA HEALTHCARE PRIVATE LIMITED', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'S R Compuer', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'STIGASOFT PVT LTD', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'STORYBIZZ MEDIA PVT LTD', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'TAH GLOBAL HEALTHTECH', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'Takshaya Bisht', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'TECH SUPERIOR CONSULTING PVT LTD', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'TRUEGRIT TECHNOLOGIES PVT LTD', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'VIPIN AGGARWAL KUDSIA AND ASSOCIATE', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'Vodafone Idea Ltd.', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'WEB SPIDERS INTERWEB PVT LTD', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'ZAO CARE TECHNOLOGY-CREDITORS', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'ZEALTHIX TECHNOLOGIES PVT LTD', group_code: 'TLY-SUNDRY-CREDITORS' },
  { name: 'ZENA HEALTHCARE PVT LTD', group_code: 'TLY-SUNDRY-CREDITORS' },
  // Bank OD A/c (2)
  { name: 'INDIAN BANK OD A/C 8291474796', group_code: 'TLY-BANK-OD-AC' },
  { name: 'INDIAN BANK OD A/C 8321472256', group_code: 'TLY-BANK-OD-AC' },
  // PEDAL START (8)
  { name: 'Avitaz Solutions LLP', group_code: 'TLY-PEDAL-START' },
  { name: 'GAGAN CHAWLA', group_code: 'TLY-PEDAL-START' },
  { name: 'Jiten Bhupendra Patel', group_code: 'TLY-PEDAL-START' },
  { name: 'Krishnendu Das', group_code: 'TLY-PEDAL-START' },
  { name: 'KUNAL CHHEDA', group_code: 'TLY-PEDAL-START' },
  { name: 'Subramanian Krishnamoorthy', group_code: 'TLY-PEDAL-START' },
  { name: 'SUNIL TRIPATHI', group_code: 'TLY-PEDAL-START' },
  { name: 'VRAJESH JHA', group_code: 'TLY-PEDAL-START' },
  // Unsecured Loans, direct (6)
  { name: 'Claim Buddy Technologies Pvt Ltd-Loan', group_code: 'TLY-UNSECURED-LOANS' },
  { name: 'DMI FINANCE PRIVATE LIMITED', group_code: 'TLY-UNSECURED-LOANS' },
  { name: 'GAUTAM CHHABRA-LOAN', group_code: 'TLY-UNSECURED-LOANS' },
  { name: 'PRABJIT SINGH GILL- LOAN', group_code: 'TLY-UNSECURED-LOANS' },
  { name: 'SATISH KUMAR PANDEY - LOAN', group_code: 'TLY-UNSECURED-LOANS' },
  { name: 'ZEALTHIX TECHNOLOGIES PVT LTD- Inv. Fin. Loan', group_code: 'TLY-UNSECURED-LOANS' },
  // Suspense A/c self-named ledger (1)
  { name: 'Suspense A/c', group_code: 'TLY-SUSPENSE-AC' },
  // Profit & Loss A/c — standard Tally default ledger, homed under Reserves & Surplus
  { name: 'Profit & Loss A/c', group_code: 'TLY-RESERVES-SURPLUS' },
  // Direct Expenses (2)
  { name: 'ANESTHESIA CHARGES', group_code: 'TLY-DIRECT-EXPENSES' },
  { name: 'Consultation Charges', group_code: 'TLY-DIRECT-EXPENSES' },
  // Employee Benefit group's own ledger (1)
  { name: 'Staff Welfare', group_code: 'TLY-EMPLOYEE-BENEFIT' },
  // Indirect Expenses, direct (46, includes the "Employee Benefit" ledger/group name clash — see ambiguity note 2)
  { name: 'ACCOUNTING CHARGES', group_code: 'TLY-INDIRECT-EXPENSES' },
  { name: 'Advertisement Expenses', group_code: 'TLY-INDIRECT-EXPENSES' },
  { name: 'Bank Charge', group_code: 'TLY-INDIRECT-EXPENSES' },
  { name: 'BLOOD CHARGE', group_code: 'TLY-INDIRECT-EXPENSES' },
  { name: 'BUSINESS PROMOTION', group_code: 'TLY-INDIRECT-EXPENSES' },
  { name: 'CLOUD CHARGES', group_code: 'TLY-INDIRECT-EXPENSES' },
  { name: 'Conveyance Expense', group_code: 'TLY-INDIRECT-EXPENSES' },
  { name: 'COURIER CHARGES', group_code: 'TLY-INDIRECT-EXPENSES' },
  { name: 'Diesel', group_code: 'TLY-INDIRECT-EXPENSES' },
  { name: 'DISALLOWED', group_code: 'TLY-INDIRECT-EXPENSES' },
  { name: 'ELECTRICITY EXPENSES', group_code: 'TLY-INDIRECT-EXPENSES' },
  { name: 'Employee Benefit', group_code: 'TLY-INDIRECT-EXPENSES' }, // ledger, distinct from the TLY-EMPLOYEE-BENEFIT group of the same name — see ambiguity note 2
  { name: 'Festival Expenses', group_code: 'TLY-INDIRECT-EXPENSES' },
  { name: 'FOOD CHARGES', group_code: 'TLY-INDIRECT-EXPENSES' },
  { name: 'Garbage Charge', group_code: 'TLY-INDIRECT-EXPENSES' },
  { name: 'HOUSEKEEPING-EXPENSE', group_code: 'TLY-INDIRECT-EXPENSES' },
  { name: 'INTEREST ON LOAN', group_code: 'TLY-INDIRECT-EXPENSES' },
  { name: 'Interest On OD Account', group_code: 'TLY-INDIRECT-EXPENSES' },
  { name: 'Interest On TDS', group_code: 'TLY-INDIRECT-EXPENSES' },
  { name: 'INVESTIGATION CHARGES', group_code: 'TLY-INDIRECT-EXPENSES' },
  { name: 'LAB CHARGES', group_code: 'TLY-INDIRECT-EXPENSES' },
  { name: 'LATE FEE CHARGE', group_code: 'TLY-INDIRECT-EXPENSES' },
  { name: 'LAUNDRY CHARGES', group_code: 'TLY-INDIRECT-EXPENSES' },
  { name: 'LEASE LICENSE', group_code: 'TLY-INDIRECT-EXPENSES' },
  { name: 'LIFT LICENSE', group_code: 'TLY-INDIRECT-EXPENSES' },
  { name: 'LINEN EXPENSES', group_code: 'TLY-INDIRECT-EXPENSES' },
  { name: 'MEDICAL GASES', group_code: 'TLY-INDIRECT-EXPENSES' },
  { name: 'Office Expenses', group_code: 'TLY-INDIRECT-EXPENSES' },
  { name: 'Printing and Stationery Charges', group_code: 'TLY-INDIRECT-EXPENSES' },
  { name: 'Processing Fee', group_code: 'TLY-INDIRECT-EXPENSES' },
  { name: 'Professional Charges', group_code: 'TLY-INDIRECT-EXPENSES' },
  { name: 'RADIOLOGY CHARGES', group_code: 'TLY-INDIRECT-EXPENSES' },
  { name: 'Refund Expenses', group_code: 'TLY-INDIRECT-EXPENSES' },
  { name: 'Regstratiions Charge', group_code: 'TLY-INDIRECT-EXPENSES' },
  { name: 'RENT', group_code: 'TLY-INDIRECT-EXPENSES' },
  { name: 'Repair & Maintance - IT Exp.', group_code: 'TLY-INDIRECT-EXPENSES' },
  { name: 'Repair & Maintenance -Building', group_code: 'TLY-INDIRECT-EXPENSES' },
  { name: 'Repair & Maintenance - Computer', group_code: 'TLY-INDIRECT-EXPENSES' },
  { name: 'Repair & Maintenance - Electricity', group_code: 'TLY-INDIRECT-EXPENSES' },
  { name: 'Repair & Maintenance- Machinery', group_code: 'TLY-INDIRECT-EXPENSES' },
  { name: 'REPAIR & MAINTENANCE- MEDICAL EQUIPMENTS', group_code: 'TLY-INDIRECT-EXPENSES' },
  { name: 'SALARIES & WAGES', group_code: 'TLY-INDIRECT-EXPENSES' },
  { name: 'SECURITY SERVICES', group_code: 'TLY-INDIRECT-EXPENSES' },
  { name: 'Short & Excess', group_code: 'TLY-INDIRECT-EXPENSES' },
  { name: 'Telephone & Internet Exp.', group_code: 'TLY-INDIRECT-EXPENSES' },
  { name: 'Website Expenses', group_code: 'TLY-INDIRECT-EXPENSES' },
  // Purchase Accounts (1)
  { name: 'MEDICINE & DISPOSABLE', group_code: 'TLY-PURCHASE-ACCOUNTS' },
  // Indirect Incomes (3)
  { name: 'Other Income', group_code: 'TLY-INDIRECT-INCOMES' },
  { name: 'Rental Equipment Charges', group_code: 'TLY-INDIRECT-INCOMES' },
  { name: 'RENT-DIALYSIS/CANTEEN', group_code: 'TLY-INDIRECT-INCOMES' },
  // Sales Accounts (2)
  { name: 'ADVANCE', group_code: 'TLY-SALES-ACCOUNTS' },
  { name: 'SALES', group_code: 'TLY-SALES-ACCOUNTS' },
];

// Sanity totals — must equal the source files' own footer counts.
export const EXPECTED_GROUP_COUNT = 37;
export const EXPECTED_LEDGER_COUNT = 346;
