"use client";

import React, { useState, useEffect } from "react";
import { AppShell } from '@/app/components/layout/AppShell';
import {
    DollarSign,
    Stethoscope,
    Pill,
    Activity,
    Plus,
    Trash2,
    Save,
    Inbox,
    Loader2
} from "lucide-react";
import { getFinanceConfig, saveFinanceConfig } from "@/app/actions/finance-config-actions";

export default function ReceptionFinancePage() {
    const [activeTab, setActiveTab] = useState("doctors");
    const [isLoading, setIsLoading] = useState(true);
    const [isSaving, setIsSaving] = useState(false);

    // Dynamic State for User Input
    const [doctors, setDoctors] = useState<any[]>([]);
    const [checkups, setCheckups] = useState<any[]>([]);
    const [medicines, setMedicines] = useState<any[]>([]);

    useEffect(() => {
        loadData();
    }, []);

    const loadData = async () => {
        setIsLoading(true);
        const res = await getFinanceConfig();
        if (res.success && res.data) {
            setDoctors(res.data.doctors || []);
            setCheckups(res.data.checkups || []);
            setMedicines(res.data.medicines || []);
        }
        setIsLoading(false);
    };

    const handleSave = async () => {
        setIsSaving(true);
        const res = await saveFinanceConfig({ doctors, checkups, medicines });
        if (res.success) {
            alert("Configuration saved successfully!");
            await loadData(); // reload actual IDs generated by server
        } else {
            alert("Failed to save: " + res.error);
        }
        setIsSaving(false);
    };

    const addCheckupRow = () => {
        setCheckups([{ id: "temp_" + Date.now(), name: "", code: "", price: "" }, ...checkups]);
    };

    const addMedicineRow = () => {
        setMedicines([{ id: "temp_" + Date.now(), name: "", comp: "", price: "" }, ...medicines]);
    };

    const updateItem = (setter: any, list: any[], id: any, field: string, value: string) => {
        setter(list.map(item => item.id === id ? { ...item, [field]: value } : item));
    };

    const removeItem = (setter: any, list: any[], id: any) => {
        setter(list.filter(item => item.id !== id));
    };

    return (
        <AppShell
            pageTitle="Finance Config"
            pageIcon={<DollarSign className="h-5 w-5" />}
        >
            <div className="space-y-8 animate-in pb-24">
                {/* Header Section */}
                <div className="flex flex-col md:flex-row md:items-end justify-between gap-4">
                    <div className="space-y-1">
                        <div className="flex items-center gap-2">
                            <div className="p-2.5 bg-emerald-100/80 rounded-xl">
                                <DollarSign className="h-6 w-6 text-emerald-600" />
                            </div>
                            <h1 className="text-2xl font-bold tracking-tight text-gray-900 border-b-2 border-transparent">
                                Finance Configuration
                            </h1>
                        </div>
                        <p className="text-gray-500 text-sm ml-12">
                            Configure dynamic doctor fees, generic test costs, and pharmacy pricing.
                        </p>
                    </div>

                    <div className="flex items-center gap-3">
                        <button
                            onClick={handleSave}
                            disabled={isLoading || isSaving}
                            className={`flex items-center gap-2 px-6 py-2 bg-emerald-600 hover:bg-emerald-700 text-white text-sm font-semibold rounded-xl shadow-md transition-all ${isSaving ? 'opacity-75 cursor-not-allowed' : ''}`}
                        >
                            {isSaving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}
                            {isSaving ? "Saving..." : "Save Configuration"}
                        </button>
                    </div>
                </div>

                {/* Main Content Area */}
                <div className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden min-h-[500px]">
                    {/* Custom Tabs Navigation */}
                    <div className="flex border-b border-gray-100 px-2 overflow-x-auto hide-scrollbar bg-gray-50/50">
                        <button
                            onClick={() => setActiveTab("doctors")}
                            className={`flex items-center gap-2 px-6 py-4 text-sm font-bold transition-colors whitespace-nowrap border-b-[3px] ${activeTab === "doctors" ? "border-emerald-500 text-emerald-600 bg-white" : "border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-200"}`}
                        >
                            <Stethoscope className="h-4 w-4" /> Doctor Fees
                        </button>
                        <button
                            onClick={() => setActiveTab("checkups")}
                            className={`flex items-center gap-2 px-6 py-4 text-sm font-bold transition-colors whitespace-nowrap border-b-[3px] ${activeTab === "checkups" ? "border-emerald-500 text-emerald-600 bg-white" : "border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-200"}`}
                        >
                            <Activity className="h-4 w-4" /> Tests & Standard Services
                        </button>
                        <button
                            onClick={() => setActiveTab("medicines")}
                            className={`flex items-center gap-2 px-6 py-4 text-sm font-bold transition-colors whitespace-nowrap border-b-[3px] ${activeTab === "medicines" ? "border-emerald-500 text-emerald-600 bg-white" : "border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-200"}`}
                        >
                            <Pill className="h-4 w-4" /> Pharmacy Pricing
                        </button>
                    </div>

                    <div className="p-6">
                        {isLoading ? (
                            <div className="py-24 flex flex-col items-center justify-center text-gray-400">
                                <Loader2 className="h-10 w-10 animate-spin text-emerald-500 mb-4" />
                                <p className="text-sm font-medium">Fetching active database configuration...</p>
                            </div>
                        ) : (
                            <>
                                {/* DOC FEES TAB */}
                                {activeTab === "doctors" && (
                                    <div className="space-y-6 animate-in fade-in slide-in-from-bottom-2 duration-300">
                                        <div className="flex items-center justify-between">
                                            <div>
                                                <h3 className="text-lg font-bold text-gray-900">Doctor Fees Database</h3>
                                                <p className="text-xs text-gray-500 mt-1">Note: Doctors are auto-synced from HR / User logs. You cannot add a text-only doctor here.</p>
                                            </div>
                                        </div>

                                        {doctors.length === 0 ? (
                                            <div className="py-16 text-center border-2 border-dashed border-gray-100 rounded-2xl flex flex-col items-center justify-center">
                                                <div className="bg-gray-50 p-4 rounded-full mb-3"><Inbox className="h-8 w-8 text-gray-300" /></div>
                                                <p className="text-gray-500 font-medium text-sm">No doctors found in the system.</p>
                                                <p className="text-gray-400 text-xs mt-1 mb-4">Please create user accounts with role "doctor" first.</p>
                                            </div>
                                        ) : (
                                            <div className="overflow-x-auto rounded-xl border border-gray-200 shadow-sm">
                                                <table className="w-full text-left border-collapse bg-white">
                                                    <thead>
                                                        <tr className="bg-gray-50/80 border-b border-gray-200">
                                                            <th className="py-3.5 px-5 text-xs font-bold text-gray-500 uppercase tracking-widest">Doctor Name</th>
                                                            <th className="py-3.5 px-5 text-xs font-bold text-gray-500 uppercase tracking-widest">Department</th>
                                                            <th className="py-3.5 px-5 text-xs font-bold text-gray-500 uppercase tracking-widest text-emerald-700">First Visit Fee (₹)</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody className="divide-y divide-gray-100">
                                                        {doctors.map((doc) => (
                                                            <tr key={doc.id} className="hover:bg-gray-50/50 transition-colors">
                                                                <td className="py-4 px-5">
                                                                    <div className="flex items-center gap-3">
                                                                        <div className="h-8 w-8 rounded-full bg-emerald-100 text-emerald-600 flex items-center justify-center font-bold text-sm">
                                                                            {doc.name ? doc.name.charAt(0).toUpperCase() : 'Dr'}
                                                                        </div>
                                                                        <span className="font-semibold text-gray-900">{doc.name || "Unnamed Doctor"}</span>
                                                                    </div>
                                                                </td>
                                                                <td className="py-4 px-5"><span className="px-2.5 py-1 bg-blue-50 text-blue-700 text-xs font-black rounded-md">{doc.dept || "General"}</span></td>
                                                                <td className="py-4 px-5">
                                                                    <div className="flex items-center gap-2 max-w-[140px]">
                                                                        <span className="text-gray-400 font-medium">₹</span>
                                                                        <input type="number" placeholder="500" value={doc.first} onChange={e => updateItem(setDoctors, doctors, doc.id, 'first', e.target.value)} className="w-full px-3 py-2 border border-gray-200 rounded-lg text-sm font-bold text-emerald-700 outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-500/20 shadow-inner" />
                                                                    </div>
                                                                </td>
                                                            </tr>
                                                        ))}
                                                    </tbody>
                                                </table>
                                            </div>
                                        )}
                                    </div>
                                )}

                                {/* CHECKUPS TAB */}
                                {activeTab === "checkups" && (
                                    <div className="space-y-6 animate-in fade-in slide-in-from-bottom-2 duration-300">
                                        <div className="flex items-center justify-between">
                                            <h3 className="text-lg font-bold text-gray-900">Standard Tests & OPD Costs</h3>
                                            <button onClick={addCheckupRow} className="flex items-center gap-2 px-4 py-2 bg-emerald-50 text-emerald-700 text-sm font-bold rounded-xl hover:bg-emerald-100 hover:shadow-sm transition-all shadow-sm border border-emerald-100">
                                                <Plus className="h-4 w-4" /> Add Service Cost
                                            </button>
                                        </div>

                                        {checkups.length === 0 ? (
                                            <div className="py-16 text-center border-2 border-dashed border-gray-100 rounded-2xl flex flex-col items-center justify-center">
                                                <div className="bg-gray-50 p-4 rounded-full mb-3"><Activity className="h-8 w-8 text-gray-300" /></div>
                                                <p className="text-gray-500 font-medium text-sm">No OPD services configured.</p>
                                                <button onClick={addCheckupRow} className="mt-4 text-emerald-600 font-bold text-sm bg-emerald-50 hover:bg-emerald-100 px-4 py-2 rounded-lg transition-colors">Create First Service</button>
                                            </div>
                                        ) : (
                                            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                                {checkups.map((item) => (
                                                    <div key={item.id} className="flex items-center justify-between p-4 border border-gray-200 rounded-2xl hover:border-emerald-300 hover:shadow-md transition-all bg-white shadow-sm group">
                                                        <div className="flex-1 space-y-2 pr-4">
                                                            <input type="text" placeholder="Service / Test Name" value={item.name} onChange={e => updateItem(setCheckups, checkups, item.id, 'name', e.target.value)} className="w-full px-3 py-1.5 border border-transparent bg-gray-50/50 hover:bg-white hover:border-gray-200 focus:bg-white focus:border-emerald-500 rounded-lg text-sm font-bold text-gray-900 outline-none transition-colors" />
                                                            <input type="text" placeholder="Service Code" value={item.code} onChange={e => updateItem(setCheckups, checkups, item.id, 'code', e.target.value)} className="w-1/2 px-3 py-1 border border-transparent bg-gray-50/50 hover:bg-white hover:border-gray-200 focus:bg-white focus:border-emerald-500 rounded-lg text-xs font-mono text-gray-500 outline-none transition-colors" />
                                                        </div>
                                                        <div className="flex items-center gap-3">
                                                            <div className="flex items-center bg-gray-50 border border-gray-200 rounded-xl overflow-hidden focus-within:ring-2 focus-within:ring-emerald-500/20 focus-within:border-emerald-500 transition-all">
                                                                <span className="pl-3 pr-1 text-gray-400 text-sm font-medium">₹</span>
                                                                <input type="number" placeholder="0" value={item.price} onChange={e => updateItem(setCheckups, checkups, item.id, 'price', e.target.value)} className="w-24 py-2.5 pr-3 bg-transparent outline-none text-sm font-black text-emerald-700 font-mono tracking-tight" />
                                                            </div>
                                                            <button onClick={() => removeItem(setCheckups, checkups, item.id)} className="p-2.5 text-red-300 opacity-50 group-hover:opacity-100 hover:text-red-500 hover:bg-red-50 rounded-xl transition-all"><Trash2 className="h-5 w-5" /></button>
                                                        </div>
                                                    </div>
                                                ))}
                                            </div>
                                        )}
                                    </div>
                                )}

                                {/* MEDICINES TAB */}
                                {activeTab === "medicines" && (
                                    <div className="space-y-6 animate-in fade-in slide-in-from-bottom-2 duration-300">
                                        <div className="flex items-center justify-between">
                                            <div>
                                                <h3 className="text-lg font-bold text-gray-900">Pharmacy Retail Pricing</h3>
                                                <p className="text-xs text-gray-500 mt-1">Manage local medicine overrides.</p>
                                            </div>
                                            <button onClick={addMedicineRow} className="flex items-center gap-2 px-4 py-2 bg-emerald-50 text-emerald-700 text-sm font-bold rounded-xl hover:bg-emerald-100 hover:shadow-sm transition-all shadow-sm border border-emerald-100">
                                                <Plus className="h-4 w-4" /> Add Custom Price
                                            </button>
                                        </div>

                                        {medicines.length === 0 ? (
                                            <div className="py-16 text-center border-2 border-dashed border-gray-100 rounded-2xl flex flex-col items-center justify-center">
                                                <div className="bg-gray-50 p-4 rounded-full mb-3"><Pill className="h-8 w-8 text-gray-300" /></div>
                                                <p className="text-gray-500 font-medium text-sm">No local medicine overrides.</p>
                                                <p className="text-gray-400 text-xs mt-1 mb-4">Prices usually sync from Central Pharmacy.</p>
                                                <button onClick={addMedicineRow} className="text-emerald-600 font-bold text-sm bg-emerald-50 hover:bg-emerald-100 px-4 py-2 rounded-lg transition-colors">Add Custom Medicine</button>
                                            </div>
                                        ) : (
                                            <div className="overflow-x-auto rounded-xl border border-gray-200 shadow-sm">
                                                <table className="w-full text-left border-collapse bg-white">
                                                    <thead>
                                                        <tr className="bg-gray-50/80 border-b border-gray-200">
                                                            <th className="py-3.5 px-5 text-xs font-bold text-gray-500 uppercase tracking-widest w-1/3">Medicine Brand</th>
                                                            <th className="py-3.5 px-5 text-xs font-bold text-gray-500 uppercase tracking-widest w-1/3">Composition</th>
                                                            <th className="py-3.5 px-5 text-xs font-bold text-gray-500 uppercase tracking-widest text-emerald-700">Unit Price (₹)</th>
                                                            <th className="py-3.5 px-5 text-xs font-bold text-gray-500 uppercase tracking-widest text-right">Delete</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody className="divide-y divide-gray-100">
                                                        {medicines.map((med) => (
                                                            <tr key={med.id} className="hover:bg-gray-50/50 transition-colors group">
                                                                <td className="py-3 px-5"><input type="text" placeholder="Brand Name" value={med.name} onChange={e => updateItem(setMedicines, medicines, med.id, 'name', e.target.value)} className="w-full px-3 py-2 border border-transparent bg-transparent hover:bg-white hover:border-gray-200 focus:bg-white focus:border-emerald-500 rounded-lg text-sm font-semibold text-gray-900 outline-none transition-all" /></td>
                                                                <td className="py-3 px-5"><input type="text" placeholder="Composition" value={med.comp} onChange={e => updateItem(setMedicines, medicines, med.id, 'comp', e.target.value)} className="w-full px-3 py-2 border border-transparent bg-transparent hover:bg-white hover:border-gray-200 focus:bg-white focus:border-emerald-500 rounded-lg text-sm text-gray-600 outline-none transition-all" /></td>
                                                                <td className="py-3 px-5">
                                                                    <div className="flex items-center gap-2 max-w-[140px]">
                                                                        <span className="text-gray-400 font-medium">₹</span>
                                                                        <input type="number" placeholder="Rs" value={med.price} onChange={e => updateItem(setMedicines, medicines, med.id, 'price', e.target.value)} step="0.5" className="w-full px-3 py-2 border border-gray-200 bg-white rounded-lg text-sm font-bold text-emerald-700 font-mono outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-500/20 shadow-inner" />
                                                                    </div>
                                                                </td>
                                                                <td className="py-3 px-5 text-right">
                                                                    <button onClick={() => removeItem(setMedicines, medicines, med.id)} className="p-2 text-red-300 opacity-50 group-hover:opacity-100 hover:text-red-600 hover:bg-red-50 rounded-xl transition-all"><Trash2 className="h-4 w-4" /></button>
                                                                </td>
                                                            </tr>
                                                        ))}
                                                    </tbody>
                                                </table>
                                            </div>
                                        )}
                                    </div>
                                )}
                            </>
                        )}
                    </div>
                </div>
            </div>
        </AppShell>
    );
}
