/**
 * lib/contracts/voice.ts
 * =====================================================================
 * FROZEN SEAM — Day 0 contract between Track A and Track B.
 * Do NOT modify without a joint PR agreed by both track owners.
 *
 * Track A produces:  RegistrationResult, VoiceSession (real impl in lib/voice/)
 * Track B consumes:  RegistrationResult, VoiceSession (mock during dev)
 * =====================================================================
 */

// Launch language set. Extend by config (not code) for future languages.
export type LanguageCode = 'en' | 'hi';

/**
 * The handoff payload Track A produces and Track B consumes.
 */
export interface RegistrationResult {
  /** String patient ID as stored in OPD_REG.patient_id (e.g. "AVN-2026-00001") */
  patientId: string;
  /** Organisation UUID — scopes ALL of Track B's DB queries */
  organisationId: string;
  /** Session language chosen in Step 1 */
  language: LanguageCode;
  /** Patient's full name — used for personalised TTS in booking steps */
  patientName: string;
  /** Optional password setup link generated by Track A */
  setupLink?: string;
}

/**
 * The shared voice kernel interface.
 * Track A owns the real implementation (lib/voice/*).
 * Track B uses a mock until integration.
 */
export interface VoiceSession {
  /** Active session language */
  readonly language: LanguageCode;
  /**
   * Capture one utterance from the patient.
   * @param expectedType - Optional hint for the STT engine (added by Track A)
   * @returns text transcription and confidence score (0–1)
   */
  listen(expectedType?: 'boolean' | 'text'): Promise<{ text: string; confidence: number }>;
  /**
   * Speak a response aloud to the patient.
   */
  speak(text: string): Promise<void>;
  /** Read a typed value from session memory */
  get<T>(key: string): T | undefined;
  /** Write a typed value to session memory */
  set<T>(key: string, value: T): void;
}

// ─────────────────────────────────────────────────────────────────────────────
// API shape contracts (frozen alongside the types above)
// ─────────────────────────────────────────────────────────────────────────────

/** Shape returned by POST /api/voice/nlu/symptoms */
export interface SymptomNLUResponse {
  specialties: string[];
  redFlags: string[];
  isEmergency: boolean;
  /** 0–1 confidence of the primary specialty mapping */
  confidence: number;
  /** Human-readable reason the assistant should speak to the patient */
  reasoning: string;
}

/** Shape of one doctor record returned by GET /api/organisations/:orgId/doctors */
export interface DoctorCard {
  id: string;
  name: string;
  specialty: string;
  consultationFee: number;
  workingHours: string;
  workingDays: string | null;
}

/** Shape of one slot returned by GET /api/doctors/:doctorId/slots */
export interface SlotCard {
  id: string;
  startTime: string; // "09:00"
  endTime: string;   // "09:30"
  date: string;      // ISO date string
}

/** Shape of the appointment creation response from POST /api/appointments */
export interface AppointmentCreationResult {
  success: boolean;
  appointmentId?: string;
  appointmentDate?: string;
  doctor?: Pick<DoctorCard, 'name' | 'specialty'>;
  error?: string;
}