/**
 * Symptom catalog — single source of truth for triage UI and rule engine.
 * Replaces hardcoded arrays in triage page and triage-actions.
 */

export const COMMON_SYMPTOMS = [
    'Fever',
    'Headache',
    'Cough',
    'Chest Pain',
    'Abdominal Pain',
    'Back Pain',
    'Nausea',
    'Vomiting',
    'Diarrhea',
    'Dizziness',
    'Shortness of Breath',
    'Fatigue',
    'Joint Pain',
    'Skin Rash',
    'Sore Throat',
    'Eye Pain',
    'Ear Pain',
    'Difficulty Breathing',
    'High Fever',
    'Severe Headache',
    'Seizure',
    'Severe Bleeding',
    'Loss of Consciousness',
    'Broken Bone',
] as const;

/** Emergency red-flag symptoms — triggers Emergency triage level */
export const EMERGENCY_SYMPTOMS = [
    'chest pain',
    'difficulty breathing',
    'severe bleeding',
    'unconscious',
    'seizure',
    'stroke symptoms',
    'severe allergic reaction',
    'anaphylaxis',
    'cardiac arrest',
    'severe burns',
    'drowning',
    'poisoning',
    'head injury',
    'spinal injury',
    'severe trauma',
    'choking',
    'heart attack',
    'shortness of breath',
    'loss of consciousness',
    'high fever above 104',
    'severe abdominal pain',
] as const;

/** Urgent symptoms — triggers Urgent triage level */
export const URGENT_SYMPTOMS = [
    'high fever',
    'persistent vomiting',
    'dehydration',
    'broken bone',
    'deep cut',
    'moderate bleeding',
    'severe headache',
    'eye injury',
    'diabetic emergency',
    'asthma attack',
    'kidney stones',
    'appendicitis',
    'blood in urine',
    'blood in stool',
    'severe diarrhea',
    'abdominal pain',
    'back pain severe',
] as const;

/** Symptom → Department routing */
export const SYMPTOM_DEPARTMENT_MAP: Record<string, string> = {
    'chest pain': 'Cardiology',
    'heart palpitations': 'Cardiology',
    'heart attack': 'Cardiology',
    'difficulty breathing': 'Pulmonology',
    'asthma attack': 'Pulmonology',
    'shortness of breath': 'Pulmonology',
    'cough': 'Pulmonology',
    'headache': 'Neurology',
    'seizure': 'Neurology',
    'stroke symptoms': 'Neurology',
    'dizziness': 'Neurology',
    'skin rash': 'Dermatology',
    'skin infection': 'Dermatology',
    'joint pain': 'Orthopedics',
    'broken bone': 'Orthopedics',
    'back pain': 'Orthopedics',
    'fracture': 'Orthopedics',
    'abdominal pain': 'Gastroenterology',
    'nausea': 'Gastroenterology',
    'vomiting': 'Gastroenterology',
    'diarrhea': 'Gastroenterology',
    'eye pain': 'Ophthalmology',
    'eye injury': 'Ophthalmology',
    'blurred vision': 'Ophthalmology',
    'ear pain': 'ENT',
    'hearing loss': 'ENT',
    'sore throat': 'ENT',
    'fever': 'General Medicine',
    'fatigue': 'General Medicine',
    'weight loss': 'General Medicine',
    'diabetes': 'Endocrinology',
    'thyroid': 'Endocrinology',
};

/** Symptom → Possible conditions */
export const SYMPTOM_CONDITION_MAP: Record<string, string[]> = {
    'chest pain': ['Angina', 'Myocardial Infarction', 'Costochondritis', 'GERD'],
    'headache': ['Migraine', 'Tension Headache', 'Sinusitis', 'Cluster Headache'],
    'fever': ['Viral Infection', 'Bacterial Infection', 'Dengue', 'Malaria', 'Typhoid'],
    'abdominal pain': ['Gastritis', 'Appendicitis', 'Kidney Stones', 'IBS'],
    'cough': ['Common Cold', 'Bronchitis', 'Pneumonia', 'Asthma', 'TB'],
    'back pain': ['Muscle Strain', 'Disc Herniation', 'Sciatica', 'Spondylitis'],
    'joint pain': ['Arthritis', 'Gout', 'Rheumatoid Arthritis', 'Lupus'],
    'dizziness': ['Vertigo', 'Hypotension', 'Anemia', 'Inner Ear Infection'],
    'nausea': ['Gastroenteritis', 'Food Poisoning', 'Pregnancy', 'Motion Sickness'],
    'skin rash': ['Contact Dermatitis', 'Eczema', 'Psoriasis', 'Fungal Infection'],
    'difficulty breathing': ['Asthma', 'COPD', 'Pneumonia', 'Pulmonary Embolism'],
    'sore throat': ['Pharyngitis', 'Tonsillitis', 'Strep Throat', 'Mononucleosis'],
};

/** Symptom → Recommended diagnostic tests */
export const SYMPTOM_TEST_MAP: Record<string, string[]> = {
    'chest pain': ['ECG', 'Troponin', 'Chest X-Ray', 'CBC'],
    'fever': ['CBC', 'Blood Culture', 'Widal Test', 'Dengue NS1'],
    'abdominal pain': ['Ultrasound Abdomen', 'CBC', 'Liver Function Test', 'Amylase'],
    'headache': ['CT Brain', 'CBC', 'ESR'],
    'cough': ['Chest X-Ray', 'Sputum Culture', 'CBC'],
    'dizziness': ['CBC', 'Blood Sugar', 'ECG', 'Blood Pressure'],
    'joint pain': ['X-Ray', 'Uric Acid', 'RA Factor', 'ESR', 'CRP'],
    'skin rash': ['Skin Scraping', 'CBC', 'IgE Levels'],
    'difficulty breathing': ['Chest X-Ray', 'ABG', 'Spirometry', 'D-Dimer'],
    'back pain': ['X-Ray Spine', 'MRI Spine', 'CBC', 'ESR'],
    'nausea': ['CBC', 'LFT', 'Pregnancy Test', 'Electrolytes'],
    'sore throat': ['Rapid Strep Test', 'Throat Culture', 'CBC'],
};
